### ISSUE TITLE
RF is 84.5 ohm??

### ISSUE THREAD

**Issue by nine-fox** [electronut/ElectronutLabs-bluey#9] opened 2017-09-28 12:17 UTC
Hi, 

Thanks a lot for developing such cool dev board. I like it very much. 

While I am still a RF learner, I have some questions about RF design. Please take a look at the part pointed in the image I attached. AppCad gave me 84.5ohm rather than 50ohm, if Er=4(FR-4), 1.6mm/1oz. May I ask, is it designed as expected? According to the design from nordic reference layout and discussion from https://devzone.nordicsemi.com/question/153755/nrf52832-antenna/, I think the expected value is 50ohm.

I do not know where to ask, so I raised an issue. Please let me know whether my calculation is correct or not, and I will close is ASAP. Thanks very much.

Yours sincerely,
Vincent

![bluey](https://user-images.githubusercontent.com/27168281/30966020-fec2991a-a489-11e7-863d-920cfd491b09.jpg)

**Comment by nine-fox** [comment] 2017-09-28 12:51
By taking a look at another break out board: https://github.com/sparkfun/nRF52832_Breakout

There width is 0.7112 while clearance is 0.1524, and the result is 51.8. I guess this result is expected

**Comment by siva-yoda** [comment] 2017-10-04 13:03
@nine-fox 
Hey Vincent,
Based on your query, we analysed our design and found out that we have clearance issue in our design. Instead of 0.15 mm, we have 0.5 mm. This is the root cause for increased impedance . Your parameters are correct, however, you won't get accurate 50 ohm impedance. You can use these parameters: Trace width 0.73 and clearance is 0.150 for 50 ohm impedance. We shall fix our impedance issue in next version.
![appcad impedance calculation](https://user-images.githubusercontent.com/22807211/31177105-8c2e78b2-a932-11e7-86d1-c8b519db5f90.PNG)

**Comment by nine-fox** [comment] 2017-10-05 13:18
Hey @SivaprakashSivan 
Thanks a lot for your investigation and response. width 0.73 and clearance is 0.150 loooks perfect. Look ing forward to the next version.

Yours sincerely,
Vincent

**Comment by electronut** [comment] 2017-10-06 02:53
Thanks @SivaprakashSivan - closing this.

**Closed as completed by electronut** 2017-10-06 02:53 UTC
